image: python:3.5.1
   
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - pep8 *
          - python run.py db upgrade
          - python run.py test