"""empty message

Revision ID: 771dbcb9989f
Revises: None
Create Date: 2016-10-14 03:38:05.771430

"""

# revision identifiers, used by Alembic.
revision = '771dbcb9989f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deputy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deputy')
    ### end Alembic commands ###
