"""empty message

Revision ID: ac913428ba37
Revises: 771dbcb9989f
Create Date: 2016-10-15 11:20:35.464928

"""

# revision identifiers, used by Alembic.
revision = 'ac913428ba37'
down_revision = '771dbcb9989f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_date',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deputy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deputy_id'], [u'deputy.id'], ),
    sa.PrimaryKeyConstraint('date', 'deputy_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_date')
    ### end Alembic commands ###
